### ISSUE TITLE
Possible issue with diacritics in opsz144

### ISSUE THREAD

**Issue by ilyaruderman** [TypeNetwork/Roboto-Flex#109]
— I've noticed that all diacritics in lowercases are moved vertically (which we normally are trying to avoid, right?)
+ Question: why are we using the comb diacritics in lowercases and not a default ones with the unicode? What are our default diacritic-glyphs for? Sorry, just trying to understand

**Comment by ilyaruderman** [comment]
Also, the values of the positioning of some of the diacritics are super strange sometimes (probably because of the scripting)
![image](https://user-images.githubusercontent.com/18192443/85868859-22e68c00-b7cb-11ea-9002-e1a5f386e3e2.png)

**Comment by sannorozco** [comment]
Yes, they’re moved up by the script, we made several tests and we needed to move them a little bit up, and we did it directly on the cmb accents. Which brings to your next question, the accents with unicode are just for charset purpose, and from those we create cmb, because some rendering engines build fallback diacritics marks using these cmb.

Finally yes, the weird numbers are result of rounding that RF doesn't do automatically.

**Comment by ilyaruderman** [comment]
I'm sorry Santiago. Still no getting it. I understand how you build comb-diacritics — from default ones. But why not to use a default ones for lowercases? I want to learn something new — and I've never saw such approach before — apologies for being pain in the neck:)

**Comment by sannorozco** [comment]
No worries! we’ll chat about this, thanks!
